---
- name: Install and keep basic utilities updated on private servers
  hosts: private_servers
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/private_servers.yml

  roles:
    - role: common
      tags: [utilities, common]
